Config/urls.py
from django.contrib import admin
from django.urls import path,include
# jwt
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
# swagger endpoints
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
# 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('song.urls')),
    path('',include('accounts.urls')),

    # APIs
    path('api/',include('home.api.urls')),
    path('api/song/',include('song.api.urls')),
    path('api/',include('accounts.api.urls')),

    ## swagger
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    ##JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

accounts/urls.py
from django.urls import path
from . import views
# 
app_name='accounts'
urlpatterns=[
    path('signup/',views.UserRegisterView.as_view(),name='signup'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('get-pro/',views.GetPremiumView.as_view(),name='get-pro'),
    path('profile/',views.ProfileView.as_view(),name='profile')


]

home/urls.py
from django.urls import path
from . import views
app_name ='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('contact-us/',views.ContactUsView.as_view(),name='contact-us')
]

song/urls.py
from django.urls import path
from . import views

app_name = 'song'
urlpatterns = [
    path('songs/',views.SongListView.as_view(),name='list'),
    path('song/<int:pk>/<slug:slug>/',views.GetSongView.as_view(),name='detail'),
    path('artists/',views.ArtistListView.as_view(),name='artists'),
    path('artist/<slug:slug>/',views.GetArtistView.as_view(),name='artist'),
    path('vote/<int:song_id>/',views.VoteView.as_view(),name='vote'),
    path('comming-soon/',views.CommingSoonSongsView.as_view(),name='comming-soon'),
    path('prousers/',views.ProUsersClass.as_view(),name='prousers'),
    path('category-related-songs/<slug:slug>/',views.GetCategorySongs.as_view()
        ,name='category-related-songs'),
    # path('category/<slug:slug>/'views.GetCategoryView.as_view(),name='category')
    
]

templates/partials/footer.html
<footer class="bg-light text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>

templates/partials/item_card.html
<div class="card col-3">
    <img class="card-img-top" src="{{value.image.url}}" alt="{{value.title}}">
    <div class="card-body">
      <a href="{{ value.get_absolute_url }}"><h5 class="card-title">{{value.title}}</h5></a>
      <p class="card-text">{{value.description}}</p>
    </div>
  </div>

templates/partials/messages.html
{% if messages %}
{% for msg in messages %}
<div class="alert alert-{{msg.tags}}"> {{msg}} </div>
{% endfor %}
{% endif %}

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg p-3">
  <a class="navbar-brand text-white" href="{% url 'home:home' %}">OnlineMusic</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- songs -->
  <a href="{% url 'song:list' %}" class="nav-link text-white">songs</a>
<!-- end songs -->
<!-- dropdown -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-light" href="#" 
            id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for category in categories %}
              <a class="dropdown-item" href="{% url 'song:category-related-songs' category.slug %}">
                {{category.title}}
              </a>
          {% endfor %}
        </div>
      </li>
<!-- end dropdown -->
<!-- dropdown2 -->
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item dropdown">

      <a class="nav-link dropdown-toggle text-warning" href="#" id="navbarDropdown" 
          role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        More
      </a>

      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a href="{% url 'song:artists' %}" class="nav-link">artists</a>
          <a href="{% url 'song:comming-soon' %}" class="nav-link">up comming songs</a>
        
        <!-- contact us -->
          <a href="{% url 'home:contact-us' %}" class="nav-link">Contact Us</a>
        <!-- end contactUs -->

        <!-- api -->
        <a href="{% url 'swagger-ui' %}" class="nav-link">API</a>
        <!-- end api -->
      </div>
    </li>
<!-- end dropdown2 -->

<!-- auth -->
{% if user.is_authenticated %}
<div class="d-flex justify-content-end">
  <li class="nav-item">
    <a href="{% url 'accounts:logout' %}" class="nav-link text-danger">log-out</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a href="{% url 'accounts:signup' %}" class="nav-link text-light">signUp</a>
  </li>
  <li class="nav-item">
    <a href="{% url 'accounts:login' %}" class="nav-link text-light">login</a>
  </li>
</div>
{% endif %}
<!-- end auth -->



</ul>
<!-- search -->
    {% if 'songs' in request.path or 'artists' in request.path %}
      <form method="get" novalidate>
          | {{search_form}}
          <input type="submit" value="search" class="btn btn-sm btn-outline-light">
      </form>
    {% endif %} 
  <!-- end search -->

</nav>