Config/urls.py
from django.contrib import admin
from django.urls import path,include
# jwt
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
# swagger endpoints
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
# 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('song.urls')),
    path('',include('accounts.urls')),

    # APIs
    path('api/',include('home.api.urls')),
    path('api/song/',include('song.api.urls')),
    path('api/',include('accounts.api.urls')),

    ## swagger
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    ##JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

home/urls.py
from django.urls import path
from . import views
app_name ='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('contact-us/',views.ContactUsView.as_view(),name='contact-us')
]

song/api/urls.py
from django.urls import path
from . import views
# 
app_name = 'song-api'
urlpatterns = [
    path('get-list/',views.GetSongListApi.as_view(),name='songs'),
    path('get/<slug:slug>/',views.GetSongApi.as_view(),name='song'),
    path('get-artists/',views.GetArtistListApi.as_view(),name='artists'),
    path('get/artist/<slug:slug>/',views.GetArtistApi.as_view(),name='artist'),
    path('get-comming-songs/',views.GetCommingSoonSongsApi.as_view(),name='comming-soon'),
    path('vote-song/<int:pk>/',views.VoteSong.as_view(),name='vote'),
    path('pro-users/',views.ProUsersOnlyView.as_view(),name='pro-users'),

]

song/urls.py
from django.urls import path
from . import views

app_name = 'song'
urlpatterns = [
    path('songs/',views.SongListView.as_view(),name='list'),
    path('song/<int:pk>/<slug:slug>/',views.GetSongView.as_view(),name='detail'),
    path('artists/',views.ArtistListView.as_view(),name='artists'),
    path('artist/<slug:slug>/',views.GetArtistView.as_view(),name='artist'),
    path('vote/<int:song_id>/',views.VoteView.as_view(),name='vote'),
    path('comming-soon/',views.CommingSoonSongsView.as_view(),name='comming-soon'),
    path('prousers/',views.ProUsersClass.as_view(),name='prousers'),
    path('category-related-songs/<slug:slug>/',views.GetCategorySongs.as_view()
        ,name='category-related-songs'),
    # path('category/<slug:slug>/'views.GetCategoryView.as_view(),name='category')
    
]

song/models.py
from email.policy import default
from tabnanny import verbose
# from PIL import Image
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from accounts.models import User
# ====================================================
class Category(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('song:category',kwargs={'slug':self.slug})  

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args,**kwargs)


    
    class Meta:
        verbose_name_plural = 'categories'

# ====================================================

class Artist(models.Model):
    name = models.CharField(max_length=200)
    slug= models.SlugField()
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('song:artist',kwargs={'slug':self.slug})

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args,**kwargs)



# ====================================================

class Song(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    description = models.CharField(max_length=400,blank=True,null=True)
    image = models.ImageField(upload_to='music/%Y/%m/%d/')
    file = models.FileField(upload_to='music/%Y/%m/%d/',blank=True,null=True)
    lyrics = models.TextField()
    artist = models.ForeignKey(Artist,on_delete=models.DO_NOTHING,related_name='songs')
    created_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('category',on_delete=models.DO_NOTHING,related_name='songs')
    link = models.CharField(max_length=90,default='')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_time']

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        # if self.image:
        #     img = Image.open(self.image.path)
        #     img.thumbnail((200,200))
        #     img.save(self.image.path)
        return super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('song:detail',kwargs={'pk':self.pk,'slug':self.slug})

    def get_vote_count(self):
        return self.votes.count()

    
# ====================================================
class SongVote(models.Model):
    user = models.ForeignKey(User ,on_delete=models.DO_NOTHING,related_name='votes')
    song = models.ForeignKey(Song ,on_delete=models.CASCADE,related_name='votes')

    def __str__(self):
        return f'{self.user} voted for {self.song.title}'

song/api/views.py
from rest_framework.views import APIView
from django.db.models import Q
from rest_framework import status
from rest_framework.response import Response
from .serializers import *
from ..models import *
from utils.custom_permissions import IsProUser
# 

class GetSongListApi(APIView):
    """ this api is to display a list of songs """
    serializer_class = SongSerializer
    def get(self,request):
        songs = Song.objects.all()
        srz_data = self.serializer_class(songs,many=True)
        return Response(data=srz_data.data,status=status.HTTP_200_OK)


class GetSongApi(APIView):
    """ this api is to display a details of a song """
    serializer_class = SongSerializer
    def get(self,request,slug):
        song = Song.objects.get(slug=slug)
        srz_data = self.serializer_class(song)
        return Response(srz_data.data,status=status.HTTP_200_OK)


class GetArtistListApi(APIView):
    """ this api is to display list of artists """
    serializer_class = ArtistSerializer
    def get(self,request):
            artists =  Artist.objects.all()
            srz_data = self.serializer_class(artists,many=True) 
            return Response(data=srz_data.data,status=status.HTTP_200_OK)

class GetArtistApi(APIView):
    """ this api is to display details of an artist """
    serializer_class = ArtistSerializer
    def get(self,request,slug):
        artist = Artist.objects.get(slug=slug)
        srz_data = self.serializer_class(artist) 
        return Response(srz_data.data,status=status.HTTP_200_OK)


class GetCommingSoonSongsApi(APIView):
    """ this api is to display list of up comming songs """
    serializer_class = SongSerializer
    def get(self,request):
        comming_songs = Song.objects.filter( Q(file='') | Q(file__isnull=True))
        srz_data = self.serializer_class(comming_songs,many=True)
        return Response(data=srz_data.data,status=status.HTTP_200_OK)


class VoteSong(APIView):
    """ this api is to vote a song or to Unvote a voted song"""
    serializer_class = SongVoteSerializer
    def post(self,request,pk):
        song = Song.objects.get(pk=pk)
        vote = SongVote.objects.filter(song=song,user=request.user)
        if vote.exists():
            vote.delete()
            data = {'message':'you unvoted this song'}
            return Response(data=data,status=status.HTTP_200_OK)
        else :
            SongVote.objects.create(song=song,user=request.user)
            data = {'message':'you voted this song'}
            return Response(data=data,status=status.HTTP_201_CREATED)


class ProUsersOnlyView(APIView):
    """ only premium uesers can enter"""
    message = 'ACCESS DENIED'
    permission_classes = [IsProUser]
    def get(self,request):
        data = {'msg':'comming soon'}
        return Response(data,status=status.HTTP_401_UNAUTHORIZED)

song/views.py
from multiprocessing import context
from re import template
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from .models import Song,Artist,Category,SongVote
from utils import search
from accounts.models import User
# Create your views here.


class GetCategorySongs(View):
    template_name = 'song/category.html'
    def get(self,request,slug):
        category = Category.objects.get(slug=slug)
        songs = category.songs.all()
        context = {'related_songs':songs,
        'category':category.title}
        return render(request,self.template_name,context)

class SongListView(View):
    template_name ='song/list.html'
    page_title = 'songs'
    def get(self,request,page=1):
        songs = Song.objects.all()
        songs = search.search(request,queryset=songs)
        # paggination
        paginator = Paginator(songs,6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        # end of paggination
        context = {'songs':page_obj,'page_title':self.page_title}
        return render(request,self.template_name,context)
    # todo : paggination

class GetSongView(View):
    template_name = 'song/detail.html'
    def get(self,request,*args,**kwargs):
        pk = kwargs.get('pk')
        slug = kwargs.get('slug')
        song = get_object_or_404(Song,pk=pk,slug=slug)
        context = {'song':song}
        return render(request,self.template_name,context)


class ArtistListView(View):
    template_name = 'song/artists.html'
    page_title = 'artists'
    def get(self,request):
        artists = Artist.objects.all()
        artists = search.search(request,queryset=artists)
        # paggination
        paginator = Paginator(artists,6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        # end of paggination          
        context = {'artists': page_obj,'page_title':self.page_title}
        return render(request,self.template_name,context)

class GetArtistView(View):
    template_name = 'song/artist_page.html'
    page_title = 'artist profile'
    def get(self,request,slug):
        artist = get_object_or_404(Artist,slug=slug)
        artist_songs = Song.objects.filter(artist__name = artist.name)
        context = {'artist': artist,'page_title':self.page_title,'artist_songs':artist_songs}
        return render(request,self.template_name,context)


class VoteView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('song:list')
        return super().dispatch(request, *args, **kwargs)

    def get(self,request,song_id):
        song = Song.objects.get(id=song_id)
        vote = SongVote.objects.filter(user=request.user ,song=song)
        if vote.exists():
            vote.delete()
            messages.success(request,'you unvoted the song','success')
            return redirect('song:detail',song.id,song.slug)
        elif not vote.exists():
            SongVote.objects.create(user=request.user,song=song).save()
            messages.success(request,'you voted the song','success')
        return redirect('song:detail',song.id,song.slug)


class CommingSoonSongsView(View):
    template_name = 'song/commingsoon.html'
    def get(self,request):
        comming_soon_songs = Song.objects.filter( Q(file='') | Q(file__isnull=True))
        comming_soon_songs = search.search(request,queryset=comming_soon_songs)
        context= {'comming_soon_songs':comming_soon_songs}
        return render(request,self.template_name,context)




        
class ProUsersClass(View):
    template_name = 'song/pro_users.html'
    def dispatch(self, request, *args, **kwargs):
        users = User.objects.filter(groups__name='premium_users')
        if not request.user in users :
            messages.warning(request,'you must pay ','warning')
            return redirect('accounts:get-pro')    
        return super().dispatch(request, *args, **kwargs)
    def get(self,request):
        return render(request,self.template_name)

song/templates/song/artist_page.html
{% extends 'base.html' %}

{% block content %}
<h3>{{artist.name}}</h3>
<hr>
<h5>{{artist.name}}'s musics</h5>
<ul>
    {% for song in artist_songs %}
        <li><a href="{{song.get_absolute_url}}">{{song.title}}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

song/templates/song/artists.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-row"> 

    {% for artist in artists %}
        <div class="card col-3">
          <a href="{{artist.get_absolute_url}}">
              <h4 class="card-body">{{artist.name}}</h4>
          </a>
        </div>
    {% endfor %}
</div>

    <div>
                    <!-- paggination -->
            <nav aria-label="...">
                <ul class="pagination">
                {% if artists.has_previous  %}
                  <li class="page-item"><a class="page-link" href="?page={{artists.previous_page_number}}">
                    {{artists.previous_page_number}}</a></li>
                {% endif %}
                
                  <li class="page-item active">
                    <a class="page-link" href="#">{{artists.number}}</a>
                  </li>
                {% if artists.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{artists.next_page_number}}">
                    {{artists.next_page_number}}</a></li>
                {% endif %}
                </ul>
              </nav>
            <!-- end of paggination -->
    </div>
{% endblock content %}

song/templates/song/category.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h4> songs in category of ''{{category}}'</h4>
        <ul>
        {% for song in related_songs %}
            <li>
                <a href="{{song.get_absolute_url}}">{{song.title}}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

song/templates/song/commingsoon.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-row"> 
    {% for song in comming_soon_songs %}
        {% include 'partials/item_card.html' with value=song %}
    {% endfor %}
</div>
{% endblock %}

song/templates/song/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="center">
        <img src="{{song.image.url}}" width="500px">
        <h4> {{song.title}} </h4>
        <p>{{song.description}}</p>
        <div>
            <h5>song lyrics :</h5>
            {{song.lyrics}}
        </div>
        {% if song.file %}
        <audio controls>
            <source src="{{song.file.url}}" type="audio/mp3">
        </audio>
        {% endif %}
    </div>
{% endblock %}
{% block side %}
    {% if user.is_authenticated %}
    <div>
        <b class="text-light">vote song:</b>
        <a href="{% url 'song:vote' song.id %}" style="text-decoration-line: none;" 
        class="btn btn-xs btn-outline-info">
            Like ({{song.get_vote_count}}) 
         </a>
    </div>
    {% endif %}
{% endblock side %}

song/templates/song/list.html
{% extends 'base.html' %}

{% block content %}
        <div class="d-flex flex-row">
            {% for song in songs %}
                {% include 'partials/item_card.html' with value=song %}
            {% endfor %}
        </div>
        <div>
          <!-- paggination -->
            <nav aria-label="...">
                <ul class="pagination">
                {% if songs.has_previous  %}
                  <li class="page-item"><a class="page-link" href="?page={{songs.previous_page_number}}">
                    {{songs.previous_page_number}}</a></li>
                {% endif %}
                
                  <li class="page-item active">
                    <a class="page-link" href="#">{{songs.number}}</a>
                  </li>
                {% if songs.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{songs.next_page_number}}">
                    {{songs.next_page_number}}</a></li>
                {% endif %}
                </ul>
              </nav>
            <!-- end of paggination -->
        </div>
{% endblock %}

song/templates/song/pro_users.html
{% extends 'base.html' %}
{% block content %}
<div>
    <b>hello pro user</b>
</div>
{% endblock %}