Config/urls.py
from django.contrib import admin
from django.urls import path,include
# jwt
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
# swagger endpoints
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
# 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('song.urls')),
    path('',include('accounts.urls')),

    # APIs
    path('api/',include('home.api.urls')),
    path('api/song/',include('song.api.urls')),
    path('api/',include('accounts.api.urls')),

    ## swagger
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    ##JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

accounts/urls.py
from django.urls import path
from . import views
# 
app_name='accounts'
urlpatterns=[
    path('signup/',views.UserRegisterView.as_view(),name='signup'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('get-pro/',views.GetPremiumView.as_view(),name='get-pro'),
    path('profile/',views.ProfileView.as_view(),name='profile')


]

home/urls.py
from django.urls import path
from . import views
app_name ='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('contact-us/',views.ContactUsView.as_view(),name='contact-us')
]

song/urls.py
from django.urls import path
from . import views

app_name = 'song'
urlpatterns = [
    path('songs/',views.SongListView.as_view(),name='list'),
    path('song/<int:pk>/<slug:slug>/',views.GetSongView.as_view(),name='detail'),
    path('artists/',views.ArtistListView.as_view(),name='artists'),
    path('artist/<slug:slug>/',views.GetArtistView.as_view(),name='artist'),
    path('vote/<int:song_id>/',views.VoteView.as_view(),name='vote'),
    path('comming-soon/',views.CommingSoonSongsView.as_view(),name='comming-soon'),
    path('prousers/',views.ProUsersClass.as_view(),name='prousers'),
    path('category-related-songs/<slug:slug>/',views.GetCategorySongs.as_view()
        ,name='category-related-songs'),
    # path('category/<slug:slug>/'views.GetCategoryView.as_view(),name='category')
    
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css bootstrap -->
    <link href="{% static 'bootstrap/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'styles/style.css' %}" type="text/css" rel="stylesheet">
    <title>MusicOnline</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <!-- navbar -->
            {% include 'partials/navbar.html' %}
            <!-- end navbar -->
            <!-- main side of website -->
            <div class="col-md-9 main" >
                <!--messages-->
                {% include 'partials/messages.html' %}
                <!--End-->
                {% block content %}
                {% endblock content %}
            </div>
            <!-- End main side of website -->
            <!-- right side of website -->
            <div class="col-md-3 side ">
                <div>
                    {% block side %}
                    <div class="p-3">
                        <a href="{% url 'song:prousers' %}" class="btn btn-sm btn-primary">premium section!</a>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="p-3">
                            <a href="{% url 'accounts:profile' %}" class="btn btn-sm btn-warning">
                                see your favorite songs!
                            </a>
                            <hr>

                        </div>
                    {% else %}
                        <div class="p-3">
                            <a href="{% url 'accounts:login' %}">login!</a>

                        </div>
                    {% endif %}
                    {% endblock side %}
                </div>
            </div>
    </div>
<!-- JS CDNs -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" 
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" 
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
crossorigin="anonymous"></script>
<!-- END JS CDNs -->
</body>
</html>